# Generated by Django 5.0.4 on 2024-07-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
